# action.yml
name: 'Build frontend'
description: 'Display given variable, build frontend and record the time when it finished'
inputs:
  input:  # id of input
    description: 'Input to display'
    required: true
    default: 'Hello World'
outputs:
  beginTime: # id of output
    description: 'The time we started building'
  endTime: # id of output
    description: 'The time we finished building'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input }}
